services:
  - type: web
    name: amrutam-backend
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        fromDatabase:
          name: amrutam-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: amrutam-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: "15m"
      - key: JWT_REFRESH_EXPIRES_IN
        value: "7d"
      - key: OTP_EXPIRES_IN
        value: "300000"
      - key: SLOT_LOCK_DURATION
        value: "300000"
    healthCheckPath: /health
    autoDeploy: true

  - type: redis
    name: amrutam-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru

databases:
  - name: amrutam-postgres
    databaseName: amrutam_db
    user: amrutam_user
    plan: starter
